name: Build firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/alvarosang14/stm32-compile:latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: |
          cmake --preset default
          cmake --build --preset default
      - uses: actions/upload-artifact@v7
        with:
          name: read_sensors_elf
          path: build/**/*.elf
          retention-days: 1